name: shared
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.11.0
  flutter: ^3.41.0

dependencies:
  env:
    path: ../env
  flutter:
    sdk: flutter
  intl: ^0.20.2
  logger: ^2.7.0
  powersync: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.2.0
