name: supabase_authentication_client
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.11.0
  flutter: ^3.41.0

dependencies:
  authentication_client:
    path: ../authentication_client
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1
  powersync_repository:
    path: ../../powersync_repository
  shared:
    path: ../../shared
  supabase_flutter: ^2.12.2
  token_storage:
    path: ../token_storage

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.2.0
