include:
  - package:very_good_analysis/analysis_options.yaml
  - package:bloc_lint/recommended.yaml
analyzer:
  errors:
    document_ignores: ignore
    lines_longer_than_80_chars: ignore
  exclude:
    - lib/l10n/gen/*
linter:
  rules:
    public_member_api_docs: false
