name: luminous_blocks_ui
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.11.0
  flutter: ^3.41.0

dependencies:
  app_ui:
    path: ../app_ui
  avatar_stack: ^1.2.0
  cached_memory_image: ^1.5.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_blurhash: ^0.9.1
  inview_notifier_list: ^4.0.1
  lumi_blocks:
    path: ../lumi_blocks
  octo_image: ^2.1.0
  powersync_repository:
    path: ../powersync_repository
  shared:
    path: ../shared
  shimmer: ^3.0.0
  smooth_video_progress: ^0.0.4
  sprung: ^3.0.1
  user_repository:
    path: ../user_repository
  video_player: ^2.11.1
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.2.0
