// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZLWEkvQqVkSbg_DAdhknSDgV_CPchbes',
    appId: '1:944562501841:web:7122d239f098fe087eedf0',
    messagingSenderId: '944562501841',
    projectId: 'flutter-luminous-clone-dev',
    authDomain: 'flutter-luminous-clone-dev.firebaseapp.com',
    storageBucket: 'flutter-luminous-clone-dev.firebasestorage.app',
    measurementId: 'G-1L4V2HCFWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPKy3X9WSTSJN_wIiuPFE--nRERlfip4E',
    appId: '1:944562501841:android:91073f76f5a34ab67eedf0',
    messagingSenderId: '944562501841',
    projectId: 'flutter-luminous-clone-dev',
    storageBucket: 'flutter-luminous-clone-dev.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlEJRMQDsPaD132sQECxXZYisyQalrsoM',
    appId: '1:944562501841:ios:c151c9713db22d307eedf0',
    messagingSenderId: '944562501841',
    projectId: 'flutter-luminous-clone-dev',
    storageBucket: 'flutter-luminous-clone-dev.firebasestorage.app',
    iosClientId: '944562501841-qa8cun6imdfsmfv3d0ujdni283c5votg.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZLWEkvQqVkSbg_DAdhknSDgV_CPchbes',
    appId: '1:944562501841:web:363da5255f9535df7eedf0',
    messagingSenderId: '944562501841',
    projectId: 'flutter-luminous-clone-dev',
    authDomain: 'flutter-luminous-clone-dev.firebaseapp.com',
    storageBucket: 'flutter-luminous-clone-dev.firebasestorage.app',
    measurementId: 'G-TV6RL0M0D0',
  );
}