name: posts_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  database_client:
    path: ../database_client
  shared:
    path: ../shared
  user_repository:
    path: ../user_repository
dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.31.0
  very_good_analysis: ^10.2.0
